### ISSUE TITLE
Step 2 of React advanced scenario console error

### ISSUE THREAD

**Issue by cntlsn** [patternfly/training-scenarios#129]
Step 2 of the PatternFly React Advanced scenario throws console error after pasting the code in the editor: the code is trying to import `./components/page` but all the files in the `./components/` folder return a 404.

I assume it could be caused by invalid links in `env-init.sh`:
The URLs of the components js files point to `module-2/assets/`
```
curl -L https://raw.githubusercontent.com/patternfly/training-scenarios/master/react/module-2/assets/header.js > ~/tutorial/src/components/header.js
curl -L https://raw.githubusercontent.com/patternfly/training-scenarios/master/react/module-2/assets/page.js > ~/tutorial/src/components/page.js
curl -L https://raw.githubusercontent.com/patternfly/training-scenarios/master/react/module-2/assets/toolbar.js > ~/tutorial/src/components/toolbar.js
```
but the files live in `components-advanced/assets/`

**Comment by christiemolloy** [comment]
Closing this issue because this has been resolved, thank you for filing the issue!
