### ISSUE TITLE
React Table Katacoda: Remove some of the CopyToClipboard

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#132]
After initial user testing, we noticed that our user wanted to type the text from the code snippet into the text editor however the copy to clipboard button was covering the text.

<img width="348" alt="Screen Shot 2019-10-31 at 10 09 33 AM" src="https://user-images.githubusercontent.com/20118816/67954651-abbf1080-fbc7-11e9-858a-cd22685d1b09.png">

We should remove this button from code snippets that are less than 4 lines.

cc: @seanforyou23

**Comment by dgutride** [comment]
@christiemolloy  - was this just a single user that you noticed this with or multiple?

**Comment by christiemolloy** [comment]
A single user but the three of us discussed that this was blocking the user from completing the action because they're unable to see the code underneath and are forced to copy text that they can't see - which makes it hard for them to know where it should go. @dgutride

**Comment by seanforyou23** [comment]
I like it, it's more in line with the approach I was leaning toward initially. I know we want to make things easy on users, but as you pointed out the copy clipboard buttons can overlay example code making it hard to read. Also, they always insert a line break (which is disruptive to the development flow) after the code snippet. I'd almost argue they perhaps even make things _too_ easy for the user to commit the lessons to memory.

My fear was that by making too many of the interactions of the tutorial revolve around copy/paste then we sacrifice the little parts of the process that actually make people learn and remember the lesson. I think it's good to not put too strict of rules around when to and not to add them, writing these tutorials is an art of itself, really. Some guidelines like generally don't add them for simple things that the user can (and should be able to) type out by hand in a reasonable amount of time would be helpful.

Question; do we have a minimum screen width that we can use as a baseline to make sure the examples are optimized? We could use one of our [desktop-sized](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss#L160-L162) breakpoints as a guide and pick a width that we'd like to ensure code snippets are not covered up at. For example below we have an example at 1450px and it looks good:

<img width="475" alt="Screen Shot 2019-10-31 at 1 22 19 PM" src="https://user-images.githubusercontent.com/5942899/67970572-95be4980-fbe1-11e9-8e96-9c4126063a7a.png">


The same example at 992px doesn't look as good:

<img width="324" alt="Screen Shot 2019-10-31 at 1 22 43 PM" src="https://user-images.githubusercontent.com/5942899/67970573-95be4980-fbe1-11e9-8d7c-792f7883ea2e.png">

If we can agree on minimum screen size, that would be yet another guideline we could use to determine when we should add them vs leave them out. WDYT?

**Comment by christiemolloy** [comment]
@seanforyou23 thanks for the feedback. I've added the point here in the Content Guidelines that George is building out, to determine at how many lines should we use a "copy to clipboard" button.  At the end of the day, the user is not relying on the button as they can still highlight text and copy/paste themselves, so this would be good to determine. If you have any other questions that you feel we need guidelines around, feel free to add them to this doc: https://docs.google.com/document/d/1F8szh3RaHAikrFcL5FolEMEjofVFDLgrDwwCZwtvheg/edit

I'm not too sure about the screen width here, I do know we're still waiting on this issue to resolve where the user will be able to resize the window pane which would help the case #96

**Comment by seanforyou23** [comment]
Sounds good. For now I've updated #124 with what you suggested, let me know if we need to do anything else, otherwise I'll close this issue once that PR is merged.

**Comment by christiemolloy** [comment]
Thanks for doing that, updates look good.

**Comment by christiemolloy** [comment]
Closing this issue because #124 was merged
