### ISSUE TITLE
React Table: Update time to 60 mins

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#133]
Update time to 60 mins as this is how long it took our test user who was a React Developer

**Comment by seanforyou23** [comment]
We spoke more about this offline and realized the 60-minute session came before a recent round of updates I just pushed which probably helped reduce the amount of time a big. For now, I've [increased the time to 45 min](https://github.com/patternfly/training-scenarios/pull/144/files#diff-86af90f0fde29c8f467867196a723ffdR5), would like to get a few more people to run through it before bumping up to 60. I think we will come down from even 45 by the time the [in-flight pagination work](https://github.com/patternfly/patternfly-react/pull/3182) is complete.

**Comment by christiemolloy** [comment]
closed because #144 was merged
