### ISSUE TITLE
React Table: Step 3 there are two step 2)'s

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#134]
<img width="120" alt="Screen Shot 2019-10-31 at 10 24 37 AM" src="https://user-images.githubusercontent.com/20118816/67955323-c940aa00-fbc8-11e9-8f0e-2828b68d3b01.png">

Also the second step 2 needs a little more support around how the cells are structured within the object. Its clear in the answer below but a little difficult at this step.

**Comment by seanforyou23** [comment]
Fixed in https://github.com/patternfly/training-scenarios/pull/124/
