### ISSUE TITLE
Wording: Table step 9

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#140]
Under step 2: "Disclaimer" is used. @seanforyou23 what was your guideline around using Disclaimer because its something we haven't used before. I'm curious if its something we should add to other modules

**Comment by seanforyou23** [comment]
Good question, I felt like it was a reality of life that we may from time to time have implementation shortcomings that are noticed/exposed in these tutorials. We should not try to hide these, but instead, face them head-on. I think users would appreciate hearing first hand and candidly about things that may be in a temporary state, or where bugs exist, or tips about upcoming features, etc.

In this case, that function (and more) that the user currently has to write by hand in this tutorial will soon be replaced by an [in-house implementation](https://github.com/patternfly/patternfly-react/pull/3182). If the user tries to plug this solution into an application with different amounts of data it will not work as good as it could. To solve that "properly" here in the tutorial would be far too much and would derail the core of the lesson so I thought it would make sense to call attention to it so users are aware that it's already on our radar and in flight. Adds a level of transparency, also.

I'm open to suggestions on how to improve it and what general guidelines we might want to put around using them. Should I just call it a "hint" and be done with it? What do you think?

**Comment by christiemolloy** [comment]
@gheake2 what are your thoughts ^

**Comment by christiemolloy** [comment]
@seanforyou23 @gheake2 

We used "pro tip" here in a similar way to how "disclaimer" was used

<img width="408" alt="Screen Shot 2019-11-01 at 3 25 49 PM" src="https://user-images.githubusercontent.com/20118816/68050656-fcb03100-fcbb-11e9-8e73-70b2def13d80.png">

**Comment by christiemolloy** [comment]
Closing this because this has been addressed in the content guidelines
