### ISSUE TITLE
React Charts: Bullet Chart

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#142]
Feedback cc: @dlabrecq 

**Step 4**
For number 3) I think you are referring to two properties here because constrainToVisibleArea is separate. Could you clarify that?

**Step 5**
For number 2) When you say locate the following code, you should update that block of code so that it includes the last two props that were added in the previous step

**Step 6**
For number 2) When you say locate the following code, you should update that block of code so that it includes the last props that were added in the previous two steps

For number 3) I think that you should split up those 5 steps into their own steps and explain what each property is doing, otherwise its very easy for the user to just copy and paste and not understand what they did.

The text in the labels is being cut off here:
<img width="821" alt="Screen Shot 2019-10-31 at 3 26 39 PM" src="https://user-images.githubusercontent.com/20118816/67979545-e38f7d80-fbf2-11e9-9967-c99b4942124d.png">

**Comment by dlabrecq** [comment]
Step 4: We want to add both properties

Step 6: I don't believe this needs to be broken into 5 steps, but I can see two; legend position/orientation, and legend data.

**Comment by christiemolloy** [comment]
Closing this because this has been addressed
