### ISSUE TITLE
React Charts: Area Chart

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#143]
**Don't implement until all information is added to this issue**

cc: @dlabrecq 

**Step 4**
Step 2) Replace: `Locate the code that looks like the following` with `Locate the code within the <ChartArea/> component` that way the user will get some extra information about what they're updating.

Step 3) Replace: `Replace that section with the following code` to `Replace that single ChartArea component with multiple ChartArea components wrapped in a ChartGroup tag`

**Step 5**
Step 2) Change `Locate the code that looks like the following` to `Locate the <Chart/> component` (update this language in other steps too)
Step 3) `Add the following property to that section` to `Add the following property to the Chart component that was located in step 2`

Reverse the order of the bullet points in this section... should start with the property that is first: `containerComponent` and then work downwards

In step 5 the containerComponent is set up like this with the `constrainToVisibleArea` prop inside, but in step 6 the `constrainToVisibleArea` prop is outside and inside `<Chart/>`
these should be consistent

<img width="380" alt="Screen Shot 2019-10-31 at 3 51 12 PM" src="https://user-images.githubusercontent.com/20118816/67981215-8c8ba780-fbf6-11e9-82c5-a37c8e26de1f.png">
<img width="416" alt="Screen Shot 2019-10-31 at 3 52 21 PM" src="https://user-images.githubusercontent.com/20118816/67981216-8c8ba780-fbf6-11e9-9ebf-93396bfdea22.png">

**Step 6**
Number 5) can you add more detail, maybe like why the ChartAxis sits above the ChartGroup but inside the Chart

Also text is being cut off here
<img width="610" alt="Screen Shot 2019-10-31 at 3 56 14 PM" src="https://user-images.githubusercontent.com/20118816/67981473-1f2c4680-fbf7-11e9-917d-638b724144a5.png">

**Step 7:**
3) Rather than just replacing that prop I think it would be good for the user to manually update all of the numbers and tell them why they are updating those numbers.

4) `Add the following properties to that section` may be confusing because they won't remember what the section is, so re-clarify that we're referring to the `<Chart/>`

**Comment by dlabrecq** [comment]
Step 6: The labels being cut off is a generic problem for all. I saw that with the new form tutorial as well, where buttons are cut off at the bottom. Perhaps we can add some default padding for all tutorials?

Step 7: I don't want the user to update each value of individually (i.e., the padding prop). Adjusting the padding is too tedious. (And we have not introduced the legend, yet.) They can adjust the padding after if they choose.

That said, I suggest we add a comment in the props like so. This is what we do in the react examples

```
padding={{
  bottom: 75,
  left: 75,
  right: 200, // Adjusted to accommodate the legend
  top: 50
}}
```

**Comment by christiemolloy** [comment]
@dlabrecq we had some more user feedback regarding Step 7 and users thought that it would be best to just update just the only value here instead of adding and replacing the entire padding block

**Comment by christiemolloy** [comment]
Closing this because it has all been addressed
