### ISSUE TITLE
Broken curl links in env-init.sh in React Advanced

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/training-scenarios#145]
Reported by @nicolethoen - Curl paths seem to be off on React Advanced demo's env-init.sh file. Project structure may have changed since it was developed; paths need to be updated so the files in the components folder show up. Right now they just 404.

**Comment by christiemolloy** [comment]
This may be related: https://github.com/patternfly/training-scenarios/issues/129

**Comment by christiemolloy** [comment]
This has been resolved now, thank you for the feedback!
