### ISSUE TITLE
React/Table: Intro -- Overall feedback

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#161]
**Note: Don't implement yet as we gather more feedback**

- [ ] Overall: hide the solution code in the solution file that comes with Katacoda (look at HTML/CSS as a guide)
- [ ] step 3 no.2 : its not clear that you have to make all the strings objects
- [ ] step 5 no.3 & no.4 may need to be reversed because users are getting confused
- [ ] step 6 no.1 "Import Pagination component from react-core" -- people don't understand what react-core is, and also you should introduce the Pagination component here
- [ ] need to have a link to hooks before you start talking about them
- [ ] step 9 : users are getting really confused here, need to break steps up

**Comment by seanforyou23** [comment]
I believe all of these issues were addressed in #224 - gonna close this, feel free to reopen if I've overlooked anything!
