### ISSUE TITLE
Updates to bullet chart tutorial

### ISSUE THREAD

**Issue by TheRealJon** [patternfly/training-scenarios#225]
Step 5 and 6 of the bullet chart tutorial have inaccurate screen shots. They show charts with multiple primary measure data points, but we only use a single data point in the provided code snippet.
![image](https://user-images.githubusercontent.com/22625502/70464700-67a81100-1a8d-11ea-89b3-b5c3867a100d.png)

**Comment by christiemolloy** [comment]
Other bullet chart issues:

- Step 2, no.3, Add the qualitativeRangeData property to the BulletChart component. Change this to the `<ChartBullet>` component.

- step 3, no. 2, there is a random tick mark at the end of this action step.
- step 3, no.4, another random tick mark at the end of the step,  also change: `Add labels property to the ChartBullet component.` to `Add the `labels` property to the `ChartBullet `component.``

- step 4, no.2, random space in front of "height"
<img width="247" alt="Screen Shot 2019-12-09 at 4 03 06 PM" src="https://user-images.githubusercontent.com/20118816/70472691-87dfcc00-1a9d-11ea-90f5-e34fb633be26.png">

- step 5, related to comment above - the screenshot doesn't match the tutorial as there is only one measure, not two.
In step 6 it shows that there are two measures:
primarySegmentedMeasureLegendData={[ { name: 'Measure 1' }, { name: 'Measure 2' } ]}

- step 6: update for consistency. "locate the `<ChartBullet/>` component"

**Comment by christiemolloy** [comment]
closing this because it has been resolved
