### ISSUE TITLE
Re-visit using sentence-case for components in back-ticks

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#275]
Component names should use sentence-case, but when components are referenced in code, should they use sentence-case or default to how they would appear in code.

Across all tutorials there is an inconsistency here and this is something I'd love clarification from @abigaeljamie on.

From @seanforyou23 :
"The columns definition is passed to the cells prop of the `table` component"
"Is strange, because lowercase table looks like the HTML table element, not the react Table component. I know there was a bit of discussion around this, is it really necessary to use the lowercase version here? Seems like if we're using backticks to represent code, it should be something a user could copy to clipboard and do a find for and get the correct result"

**Comment by abigaeljamie** [comment]
Hey, @christiemolloy ! Whatever's easiest for developing here. I think defaulting to how they look in code is fine (so in back ticks, they'd be capitalized). Then when we talk about the components outside of code, we can continue using sentence case.
