### ISSUE TITLE
Breaking Change update: React components > Table Tutorial

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#289]
Once #280 is closed..

Investigate if https://www.katacoda.com/patternfly/courses/react-components/table-intro will need to be updated to match the changes made to certain components during the breaking change period, and update the tutorial

**Comment by seanforyou23** [comment]
I just went through this tutorial and everything appears to still be working just fine. Closing this, for now, feel free to reopen in case I missed anything!
