### ISSUE TITLE
html/css module 3 - refinements

### ISSUE THREAD

**Issue by jgiardino** [patternfly/training-scenarios#55]
Per group review, some suggestions were captured in a [google document](https://docs.google.com/document/d/1qaqXL9Jpz8Sgjak3li7TuMjQ4VfOyS6aP3alza3-gbM/edit?usp=sharing). If feedback isn't clear, feel free to post comments in the google doc for clarification.

**Comment by christiemolloy** [comment]
Closing this issue as this has been resolved
