### ISSUE TITLE
Katacoda editor - files save too quickly instead of waiting for users to pause on input

### ISSUE THREAD

**Issue by dgutride** [patternfly/training-scenarios#89]
Currently - when editing html/scss/js files, the file saves after each character is entered.  This leads to the node process that watches the files recompiling the files and then reloading the iframe.  If a user types quickly, it's possible that the save and watch will even miss a final character, leaving the iframe in an unusable state until the user manually intervenes by right-clicking and reloading the iframe.

We'd like to see if it's possible to change the way files are saved.  If the keypresses can be tracked and only save if there is a delay after a keypress of more than some configurable number of milliseconds, that would be really helpful.  This is basically a save when I stop typing option.

**Comment by gsoria** [comment]
We've added in Katacoda side a property to define the delay to save file after the user stops typing.
In the file `index.json` there is a new property `delayToSaveFileAfterStopTypingMilliseconds` in environment, as an example:

```
  "environment": {
    "showdashboard": true,
    "delayToSaveFileAfterStopTypingMilliseconds": 2000,
    "dashboards": [
      {"name": "Web Application", "port": 3000}
    ],
    "uilayout": "editor-iframe-split",
    "uisettings": "javascript",
    "exclusionPatterns": ["._*", "package.json", "package-lock.json", "node_modules*", "public*", "serviceWorker*"],
    "hideHiddenFiles": true
  },
```

The changes in Katacoda are available in beta for now:

An example can be seen in this profile:
https://beta.katacoda.com/vj0n4ijxw/

**Comment by dgutride** [comment]
@gsoria  - the delay after typing works great - we did notice that it will immediately save if we copy/paste the text in.  Is there another setting we should use or is that expected behaviour?

**Comment by dgutride** [comment]
This is great!  Thanks @gsoria
