### ISSUE TITLE
Add failsafe reload button to the preview pane

### ISSUE THREAD

**Issue by dgutride** [patternfly/training-scenarios#91]
If the preview pane ever does get out of sync with the code or something hiccups, a small reload button would be useful to get back in sync.

**Comment by gsoria** [comment]
We've added in Katacoda side the reload button for the iframe.

![reload-button](https://user-images.githubusercontent.com/5870211/63964588-4aa28180-ca4c-11e9-83bd-bee8f3b43b2c.png)

The changes in Katacoda are available in beta for now. An example can be seen in this profile:
https://beta.katacoda.com/vj0n4ijxw/

**Comment by dgutride** [comment]
This looks great - thanks @gsoria
