### ISSUE TITLE
Katacoda code editor - format on copy/paste or save

### ISSUE THREAD

**Issue by dgutride** [patternfly/training-scenarios#92]
The html/js editor window would really benefit from a format option.  Users would copy/paste the code and then spend time reformatting it fairly consistently in our tests.  If there was a way, even with just copy/paste code to have it formatted correctly on entry, that would be a help.

**Comment by gsoria** [comment]
Hi @dgutride and @christiemolloy :), I updated the PR https://github.com/patternfly/training-scenarios/pull/100 related to this issue.
