### ISSUE TITLE
Katacoda - add verification step on next

### ISSUE THREAD

**Issue by dgutride** [patternfly/training-scenarios#95]
Users would like to have their answers checked in the editor before moving to the next step.  Ability to compare code in the editor with the solution code, across 1-2 files in the editor, while (potentially) hiding the solution code from the UI would be helpful.

**Comment by BenHall** [comment]
We have the ability to verify if the user has completed a task by running a bash script in the background. 

Example at: 
https://github.com/katacoda/scenario-examples/tree/master/verified-steps
https://katacoda.com/scenario-examples/scenarios/verified-steps

Or did you want more of a Git Diff experience where users can see the solution and their answer "side-by-side"?

**Comment by christiemolloy** [comment]
This can be closed now
